name: Major Release Check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  major_release_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for Breaking Changes
        id: breaking_changes
        run: |
          bash ./.github/workflows/scripts/check_breaking_changes.sh