name: Major Release Check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  major_release_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for Breaking Changes
        id: breaking_changes
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git log --pretty=format:"%s" origin/main..FETCH_HEAD | grep -i "BREAKING CHANGE" > breaking_changes.txt
            # If there are breaking changes and the PR is not comming from development. Fail the build
            if [ -s breaking_changes.txt ] and [ ${{ github.event.pull_request.base.ref }} != "development" ]; then
                echo "Breaking Changes Detected on a non-development branch. Please merge into development first."
                exit 1
            else
                echo "No breaking changes. Proceeding with the build."
                exit 0
            fi