name: Major Release Check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR commits
        id: breaking_changes
        run: |
          // Fetch the commits for this PR
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          // Do a Git Log looking for the string "BREAKING CHANGE"
          git log --pretty=format:"%s" origin/main..FETCH_HEAD | grep -i "BREAKING CHANGE" > breaking_changes.txt
          // If the file is empty, exit with a 0
            if [ -s breaking_changes.txt ]; then
                echo "There are breaking changes"
                exit 1
            else
                echo "No breaking changes"
                exit 0
            fi