name: Semantic Release (Pre-Release)

on:
    workflow_dispatch: # Allows manual invocation

jobs:
  pre-release:
    runs-on: ubuntu-latest
    concurrency: pre-release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v8.7.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true