name: Semantic Release (Release)

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v8.7.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

  sync-development:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Merge main into development
        uses: devmasx/merge-branch@1.4.0
        with:
          target_branch: development
          from_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
