name: Sync Development Branch

on:
  push:
    branches:
      - main

jobs:
  merge-master-back-to-dev:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Merge branch
      uses: devmasx/merge-branch@1.4.0
      with:
        from_branch: main
        target_branch: development
        github_token: ${{ secrets.GITHUB_TOKEN }}