name: Sync Development Branch

on:
  repository_dispatch:
    types: [sync-development]

jobs:

  sync-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge main into development
        run: |
          git checkout development
          git merge main
          git push origin development